/* eslint-disable @typescript-eslint/no-explicit-any */
import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { AdminPageHeader } from "@/components/admin/admin-ui";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/auth/admin";

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
async function saveMentor(formData:FormData){"use server";await requireAdmin();const db=createAdminClient()!;const id=String(formData.get("id"));const languages=String(formData.get("languages")).split(",").map(v=>v.trim()).filter(Boolean);const topics=String(formData.get("topics")).split(",").map(v=>v.trim()).filter(Boolean);await db.from("mentors").update({offering_id:String(formData.get("offeringId")),full_name:String(formData.get("fullName")),slug:slugify(String(formData.get("slug"))),email_private:String(formData.get("email")),semester:Number(formData.get("semester")),graduation_year:Number(formData.get("graduationYear")),bio:String(formData.get("bio")),languages,profile_image_url:String(formData.get("profileImageUrl"))||null,verification_status:String(formData.get("verificationStatus")),mentor_status:String(formData.get("mentorStatus")),availability_notes:String(formData.get("availabilityNotes"))||null}).eq("id",id);await db.from("mentor_topic_links").delete().eq("mentor_id",id);for(const name of topics){const slug=slugify(name);const {data:topic}=await db.from("mentor_topics").upsert({name,slug},{onConflict:"slug"}).select("id").single();if(topic)await db.from("mentor_topic_links").insert({mentor_id:id,topic_id:topic.id});}revalidatePath(`/admin/mentors/${id}`);revalidatePath("/admin/mentors");}

export default async function MentorEditPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const db=createAdminClient()!;const [{data:mentor},{data:offerings},{data:links}]=await Promise.all([db.from("mentors").select("*").eq("id",id).maybeSingle(),db.from("admin_program_offerings").select("id,degree_short_name,institution_code,city,status").eq("active",true).order("degree_short_name"),db.from("mentor_topic_links").select("mentor_topics(name)").eq("mentor_id",id)]);if(!mentor)notFound();const topics=(links??[]).map((link:any)=>link.mentor_topics?.name).filter(Boolean).join(", ");return <><AdminPageHeader eyebrow="EDIT MENTOR" title={mentor.full_name} copy="Private contact details never appear in public mentor queries."/><form action={saveMentor} className="admin-card admin-form form-grid"><input type="hidden" name="id" value={id}/><label>Full name<input name="fullName" defaultValue={mentor.full_name} required/></label><label>Private email<input name="email" type="email" defaultValue={mentor.email_private} required/></label><label className="full-field">Program offering<select name="offeringId" defaultValue={mentor.offering_id}>{offerings?.map((row:any)=><option value={row.id} key={row.id}>{row.degree_short_name} — {row.institution_code}, {row.city}</option>)}</select></label><label>Semester<input name="semester" type="number" min="1" max="12" defaultValue={mentor.semester} required/></label><label>Graduation year<input name="graduationYear" type="number" defaultValue={mentor.graduation_year} required/></label><label>Public slug<input name="slug" defaultValue={mentor.slug} required/></label><label>Profile image URL<input name="profileImageUrl" type="url" defaultValue={mentor.profile_image_url??""}/></label><label className="full-field">Bio<textarea name="bio" rows={5} defaultValue={mentor.bio} required/></label><label className="full-field">Topics (comma separated)<input name="topics" defaultValue={topics} required/></label><label>Languages<input name="languages" defaultValue={(mentor.languages??[]).join(", ")} required/></label><label>Availability note<input name="availabilityNotes" defaultValue={mentor.availability_notes??""}/></label><label>Verification<select name="verificationStatus" defaultValue={mentor.verification_status}><option>pending</option><option>verified</option><option>rejected</option></select></label><label>Status<select name="mentorStatus" defaultValue={mentor.mentor_status}><option>active</option><option>paused</option><option>archived</option></select></label><button className="button">Save mentor profile</button></form></>}
