import { NextResponse } from "next/server";
import { mentorApplicationSchema } from "@/lib/validation/schemas";
import { createAdminClient } from "@/lib/supabase/admin";
import { checkRateLimit } from "@/lib/rate-limit";
import { sendEmail } from "@/lib/email";
import { env } from "@/lib/env";

export async function POST(request: Request) {
  const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? "unknown"; const rate = checkRateLimit(`mentor:${ip}`, 4); if (!rate.allowed) return NextResponse.json({ message: "Too many applications from this connection. Please wait and try again." }, { status: 429 });
  try { const result = mentorApplicationSchema.safeParse(await request.json()); if (!result.success) return NextResponse.json({ message: result.error.issues[0]?.message ?? "Please check the form." }, { status: 400 }); const supabase = createAdminClient(); if (!supabase) return NextResponse.json({ message: "Applications are being configured. Your answers are still on this page — please try again shortly." }, { status: 503 }); const input = result.data; const { data: offering } = await supabase.from("program_offerings").select("id").eq("public_id", input.offeringId).eq("active", true).maybeSingle(); if (!offering) return NextResponse.json({ message: "Choose a valid current program offering." }, { status: 400 }); const { data: created, error } = await supabase.from("mentor_applications").insert({ full_name: input.fullName, nust_email: input.nustEmail, offering_id: offering.id, semester: input.semester, graduation_year: input.graduationYear, bio: input.bio, reason: input.reason, topics: input.topics, languages: input.languages, availability: input.availability, linkedin_url: input.linkedinUrl || null, verification_consent: input.verificationConsent, code_of_conduct_agreement: input.codeOfConduct, status: "pending" }).select("id").single(); if (error) { console.error("mentor_application_insert_failed", error.code); return NextResponse.json({ message: "We couldn’t send your application. Please try again." }, { status: 500 }); } await Promise.allSettled([sendEmail({ to: input.nustEmail, subject: "Your PageForward mentor application", html: "<h1>Thank you for stepping forward.</h1><p>We’ll review your application and verify your NUST student status before any profile is published.</p>" }), ...(env.adminNotificationEmail ? [sendEmail({ to: env.adminNotificationEmail, subject: "New PageForward mentor application", html: `<p>A mentor application is ready for review.</p><p>Reference: ${created.id}</p>` })] : [])]); return NextResponse.json({ ok: true }, { status: 201 }); } catch (error) { console.error("mentor_application_unhandled", error instanceof Error ? error.message : "unknown"); return NextResponse.json({ message: "We couldn’t send your application. Please try again." }, { status: 500 }); }
}
