/* eslint-disable @typescript-eslint/no-explicit-any */
import { revalidatePath } from "next/cache";
import { AdminPageHeader, EmptyAdminState } from "@/components/admin/admin-ui";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/auth/admin";
import { sendEmail } from "@/lib/email";
import { env } from "@/lib/env";

function makeToken(){const bytes=crypto.getRandomValues(new Uint8Array(32));return Array.from(bytes).map(value=>value.toString(16).padStart(2,"0")).join("");}
async function hashToken(token:string){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return Array.from(new Uint8Array(hash)).map(value=>value.toString(16).padStart(2,"0")).join("");}
async function updateSession(formData:FormData){"use server";await requireAdmin();const db=createAdminClient()!;const id=String(formData.get("id"));const status=String(formData.get("status"));const {data:session}=await db.from("admin_sessions").select("*").eq("id",id).single();if(!session)return;const update:Record<string,unknown>={status};if(status==="completed"){update.completed_at=new Date().toISOString();await db.from("guidance_requests").update({status:"completed"}).eq("id",session.guidance_request_id);if(!session.feedback_token_hash){const token=makeToken();update.feedback_token_hash=await hashToken(token);const base=`${env.siteUrl}/feedback/${token}`;await Promise.allSettled([sendEmail({to:session.student_email,subject:"How was your PageForward conversation?",html:`<h1>Did the conversation help?</h1><p>Your private feedback helps us improve.</p><p><a href="${base}">Share student feedback</a></p>`}),sendEmail({to:session.mentor_email,subject:"A quick PageForward mentor check-in",html:`<h1>How did the session go?</h1><p><a href="${base}?for=mentor">Share mentor feedback</a></p>`})]);}}await db.from("sessions").update(update).eq("id",id);revalidatePath("/admin/sessions");revalidatePath("/admin");}

export default async function SessionsPage(){const db=createAdminClient()!;const {data}=await db.from("admin_sessions").select("*").order("scheduled_start",{ascending:false}).limit(200);return <><AdminPageHeader eyebrow="SESSIONS" title="Keep every meeting on track." copy="Times are stored in UTC and shown here in Pakistan time."/>{data?.length?<div className="admin-table-wrap"><table><thead><tr><th>Student</th><th>Mentor</th><th>Program</th><th>Scheduled (PKT)</th><th>Provider</th><th>Status</th><th>Meeting</th></tr></thead><tbody>{data.map((row:any)=><tr key={row.id}><td>{row.student_name}</td><td>{row.mentor_name}</td><td>{row.degree_short_name}<small>{row.institution_code} · {row.city}</small></td><td>{row.scheduled_start?new Intl.DateTimeFormat("en-PK",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Karachi"}).format(new Date(row.scheduled_start)):"Not set"}</td><td>Google Meet</td><td><form action={updateSession} className="inline-admin-form"><input type="hidden" name="id" value={row.id}/><select name="status" defaultValue={row.status}>{["proposed","confirmed","completed","cancelled","no_show_student","no_show_mentor"].map(status=><option key={status}>{status}</option>)}</select><button>Save</button></form></td><td>{row.meeting_url?<a href={row.meeting_url} target="_blank" rel="noreferrer">Open ↗</a>:"—"}</td></tr>)}</tbody></table></div>:<EmptyAdminState title="No sessions scheduled" copy="Schedule a session from an open guidance request."/>}</>}
