/* eslint-disable @typescript-eslint/no-explicit-any */
import { revalidatePath } from "next/cache";
import { AdminPageHeader, EmptyAdminState } from "@/components/admin/admin-ui";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/auth/admin";
import { programOfferings } from "@/lib/catalog";
import Link from "next/link";

function slugify(value:string){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
async function manageMentor(formData:FormData){"use server";await requireAdmin();const db=createAdminClient()!;const action=String(formData.get("action"));if(action==="status"){await db.from("mentors").update({mentor_status:String(formData.get("mentorStatus")),verification_status:String(formData.get("verificationStatus"))}).eq("id",String(formData.get("id")));}if(action==="create"){const publicId=String(formData.get("offeringId"));const {data:offering}=await db.from("program_offerings").select("id").eq("public_id",publicId).single();const languages=String(formData.get("languages")).split(",").map(v=>v.trim()).filter(Boolean);const topics=String(formData.get("topics")).split(",").map(v=>v.trim()).filter(Boolean);const {data:mentor,error}=await db.from("mentors").insert({offering_id:offering!.id,full_name:String(formData.get("fullName")),slug:slugify(String(formData.get("slug"))||String(formData.get("fullName"))),email_private:String(formData.get("email")),semester:Number(formData.get("semester")),graduation_year:Number(formData.get("graduationYear")),bio:String(formData.get("bio")),languages,profile_image_url:String(formData.get("profileImageUrl"))||null,verification_status:"verified",mentor_status:"active",availability_notes:String(formData.get("availabilityNotes"))||null}).select("id").single();if(!error&&mentor){for(const topicName of topics){const topicSlug=slugify(topicName);const {data:topic}=await db.from("mentor_topics").upsert({name:topicName,slug:topicSlug},{onConflict:"slug"}).select("id").single();if(topic)await db.from("mentor_topic_links").upsert({mentor_id:mentor.id,topic_id:topic.id});}}}revalidatePath("/admin/mentors");}

export default async function MentorsPage(){const db=createAdminClient()!;const {data}=await db.from("admin_mentors").select("*").order("created_at",{ascending:false});return <><AdminPageHeader eyebrow="MENTORS" title="Build trustworthy program coverage." copy="Only verified, approved mentors become public."/><details className="admin-create-panel"><summary>Add a verified mentor <span>+</span></summary><form action={manageMentor} className="admin-form form-grid"><input type="hidden" name="action" value="create"/><label>Full name<input name="fullName" required/></label><label>Private email<input name="email" type="email" required/></label><label className="full-field">Program offering<select name="offeringId" required><option value="">Choose offering</option>{programOfferings.filter(o=>o.status==="current").map(o=><option value={o.id} key={o.id}>{o.degreeShortName} — {o.institutionCode}, {o.city}</option>)}</select></label><label>Semester<input name="semester" type="number" min="1" max="12" required/></label><label>Graduation year<input name="graduationYear" type="number" required/></label><label>Public slug<input name="slug" placeholder="generated-from-name"/></label><label>Profile image URL<input name="profileImageUrl" type="url"/></label><label className="full-field">Bio<textarea name="bio" rows={4} required/></label><label className="full-field">Topics (comma separated)<input name="topics" placeholder="Academics, Campus life, Internships" required/></label><label>Languages<input name="languages" placeholder="English, Urdu" required/></label><label>Availability note<input name="availabilityNotes"/></label><button className="button">Create mentor</button></form></details>{data?.length?<div className="admin-table-wrap"><table><thead><tr><th>Mentor</th><th>Program</th><th>Semester</th><th>Verification</th><th>Status</th><th>Change</th></tr></thead><tbody>{data.map((row:any)=><tr key={row.id}><td><b>{row.full_name}</b><small>{row.email_private}</small></td><td>{row.degree_short_name}<small>{row.institution_code} · {row.city}</small></td><td>{row.semester}</td><td>{row.verification_status}</td><td><span className={`admin-status ${row.mentor_status}`}>{row.mentor_status}</span></td><td><form action={manageMentor} className="inline-admin-form"><input type="hidden" name="action" value="status"/><input type="hidden" name="id" value={row.id}/><select name="verificationStatus" defaultValue={row.verification_status}><option>pending</option><option>verified</option><option>rejected</option></select><select name="mentorStatus" defaultValue={row.mentor_status}><option>active</option><option>paused</option><option>archived</option></select><button>Save</button><Link href={`/admin/mentors/${row.id}`}>Edit →</Link></form></td></tr>)}</tbody></table></div>:<EmptyAdminState title="No mentors yet" copy="Create a mentor only after student status has been verified."/>}</>}
