/* eslint-disable @typescript-eslint/no-explicit-any */
import { notFound } from "next/navigation";
import { revalidatePath } from "next/cache";
import { AdminPageHeader } from "@/components/admin/admin-ui";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/auth/admin";

function localTimeToUtc(value:string,timezone:string){return new Date(timezone==="Asia/Karachi"?`${value}:00+05:00`:value).toISOString();}
async function updateRequest(formData:FormData){"use server";await requireAdmin();const db=createAdminClient()!;const id=String(formData.get("id"));const action=String(formData.get("action"));if(action==="update"){await db.from("guidance_requests").update({status:String(formData.get("status")),preferred_mentor_id:String(formData.get("mentorId"))||null,internal_notes:String(formData.get("internalNotes"))||null}).eq("id",id);}if(action==="schedule"){const start=String(formData.get("scheduledStart"));const end=String(formData.get("scheduledEnd"));const mentorId=String(formData.get("mentorId"));const timezone=String(formData.get("timezone"))||"Asia/Karachi";await db.from("sessions").upsert({guidance_request_id:id,mentor_id:mentorId,scheduled_start:localTimeToUtc(start,timezone),scheduled_end:localTimeToUtc(end,timezone),timezone,meeting_provider:"google_meet",meeting_url:String(formData.get("meetingUrl")),status:"confirmed"},{onConflict:"guidance_request_id"});await db.from("guidance_requests").update({status:"scheduled",preferred_mentor_id:mentorId}).eq("id",id);}revalidatePath(`/admin/requests/${id}`);revalidatePath("/admin/requests");}

export default async function AdminRequestDetail({params}:{params:Promise<{id:string}>}){const {id}=await params;const db=createAdminClient()!;const {data:request}=await db.from("admin_request_queue").select("*").eq("id",id).maybeSingle();if(!request)notFound();const {data:mentors}=await db.from("mentors").select("id,full_name,mentor_status,verification_status").eq("offering_id",request.offering_id).eq("mentor_status","active").eq("verification_status","verified");return <><AdminPageHeader eyebrow="REQUEST DETAIL" title={request.student_name} copy={`${request.degree_short_name} · ${request.institution_code} · ${request.city}`}/><div className="admin-detail-grid"><section className="admin-card"><h2>Student context</h2><dl><dt>Email</dt><dd>{request.student_email}</dd><dt>Phone</dt><dd>{request.phone_optional||"Not provided"}</dd><dt>School / college</dt><dd>{request.school_college}</dd><dt>Education level</dt><dd>{request.education_level}</dd><dt>Under 18</dt><dd>{request.under_18?"Yes — guardian acknowledged":"No"}</dd><dt>Why this program</dt><dd>{request.reason}</dd><dt>Questions</dt><dd>{request.questions}</dd><dt>Availability</dt><dd>{request.availability}</dd></dl></section><div><form action={updateRequest} className="admin-card admin-form"><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value="update"/><h2>Match & status</h2><label>Status<select name="status" defaultValue={request.status}>{["new","reviewing","matching","mentor_contacted","scheduled","completed","cancelled","waitlisted"].map(s=><option key={s}>{s}</option>)}</select></label><label>Assigned mentor<select name="mentorId" defaultValue={request.preferred_mentor_id??""}><option value="">Not assigned</option>{mentors?.map((mentor:any)=><option key={mentor.id} value={mentor.id}>{mentor.full_name}</option>)}</select></label><label>Internal note<textarea name="internalNotes" rows={6} defaultValue={request.internal_notes??""}/></label><button className="button">Save changes</button></form><form action={updateRequest} className="admin-card admin-form"><input type="hidden" name="id" value={id}/><input type="hidden" name="action" value="schedule"/><h2>Schedule Google Meet</h2><label>Mentor<select name="mentorId" required defaultValue={request.preferred_mentor_id??""}><option value="" disabled>Choose mentor</option>{mentors?.map((mentor:any)=><option key={mentor.id} value={mentor.id}>{mentor.full_name}</option>)}</select></label><label>Start<input name="scheduledStart" type="datetime-local" required/></label><label>End<input name="scheduledEnd" type="datetime-local" required/></label><label>Timezone<input name="timezone" defaultValue="Asia/Karachi" required/></label><label>Google Meet URL<input name="meetingUrl" type="url" pattern="https://.*" required/></label><button className="button">Confirm session</button></form></div></div></>}
