"use client";
import { FormEvent, useState } from "react";

export function FeedbackForm({ token, respondentType }: { token: string; respondentType: "student" | "mentor" }) {
  const [status, setStatus] = useState<"idle"|"sending"|"success"|"error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); const form = new FormData(event.currentTarget); const data = Object.fromEntries(form.entries()); const response = await fetch("/api/feedback", { method:"POST", headers:{"Content-Type":"application/json"}, body: JSON.stringify({ ...data, token, respondentType, overallRating:Number(data.overallRating), clarityRating:Number(data.clarityRating), mentorRating:data.mentorRating?Number(data.mentorRating):undefined, recommend:data.recommend==="yes", testimonialPermission:data.testimonialPermission==="on", studentAttended:data.studentAttended==="yes", additionalGuidanceNeeded:data.additionalGuidanceNeeded==="yes" }) }); setStatus(response.ok ? "success" : "error"); }
  if (status === "success") return <div className="confirmation-card"><span className="confirmation-check">✓</span><h1>Thank you for helping us improve.</h1><p>Your feedback helps PageForward make future conversations more useful and safer.</p></div>;
  return <form className="pf-form feedback-form" onSubmit={submit}>{respondentType === "mentor" ? <><label>Did the student attend?<select name="studentAttended" required><option value="yes">Yes</option><option value="no">No</option></select></label><label>What topics did you discuss?<textarea name="comments" rows={4} /></label><label>Is additional guidance needed?<select name="additionalGuidanceNeeded"><option value="no">No</option><option value="yes">Yes</option></select></label><label>Any conduct or safety concerns?<textarea name="safetyConcern" rows={3} /></label><input type="hidden" name="overallRating" value="5" /><input type="hidden" name="clarityRating" value="5" /><input type="hidden" name="recommend" value="yes" /></> : <><label>Overall usefulness (1–5)<input name="overallRating" type="number" min="1" max="5" required /></label><label>Did this conversation make your decision clearer?<select name="clarityRating" required><option value="5">Yes</option><option value="3">Somewhat</option><option value="1">No</option></select></label><label>Mentor helpfulness (1–5)<input name="mentorRating" type="number" min="1" max="5" required /></label><label>What was most useful?<textarea name="comments" rows={4} /></label><label>Would you recommend PageForward?<select name="recommend"><option value="yes">Yes</option><option value="no">No</option></select></label><label>Optional testimonial<textarea name="testimonial" rows={3} /></label><label className="checkbox-field"><input type="checkbox" name="testimonialPermission" /><span>PageForward may use this testimonial publicly.</span></label></>}<input className="honeypot" name="website" tabIndex={-1} /><button className="button form-submit" disabled={status === "sending"}>{status === "sending" ? "Sending…" : "Submit feedback"}<span>→</span></button>{status === "error" ? <p className="form-error" role="alert">We couldn’t send your feedback. Please try again.</p> : null}</form>;
}
