"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { offeringLabel, type ProgramOffering } from "@/lib/catalog";
import { trackEvent } from "@/lib/analytics";

const topics = ["Academics", "Curriculum", "Workload", "Campus life", "Societies", "Internships", "Career options", "First year", "University transition", "Research", "Hostel life"];

export function MentorApplicationForm({ offerings, initialOffering = "" }: { offerings: ProgramOffering[]; initialOffering?: string }) {
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle"); const [error, setError] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending"); setError(""); trackEvent("mentor_application_started"); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); const chosenTopics = form.getAll("topics"); const languages = String(payload.languages ?? "").split(",").map((item) => item.trim()).filter(Boolean);
    const response = await fetch("/api/mentor-applications", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, topics: chosenTopics, languages, verificationConsent: payload.verificationConsent === "on", codeOfConduct: payload.codeOfConduct === "on" }) });
    if (response.ok) { setStatus("success"); trackEvent("mentor_application_completed"); window.scrollTo({ top: 0, behavior: "smooth" }); return; }
    const body = await response.json().catch(() => ({})) as { message?: string }; setError(body.message ?? "We couldn’t send your application. Your answers are still on this page — please try again."); setStatus("error");
  }
  if (status === "success") return <div className="confirmation-card"><span className="confirmation-check">✓</span><p className="eyebrow">APPLICATION RECEIVED</p><h1>Thank you for stepping forward.</h1><p>The PageForward team will review your details and verify your NUST student status before any profile is published.</p><div className="confirmation-steps"><span><b>1</b>Application received</span><i>→</i><span><b>2</b>Status verified</span><i>→</i><span><b>3</b>Profile approved</span></div><Link className="button" href="/">Back to PageForward <span>→</span></Link></div>;
  return <form className="pf-form" onSubmit={submit} noValidate><fieldset><legend>Your NUST details <span>01</span></legend><div className="field-grid"><label>Full name<input name="fullName" required autoComplete="name" /></label><label>NUST email<input name="nustEmail" type="email" required autoComplete="email" placeholder="you@nust.edu.pk" /></label><label className="full-field">Exact program offering<select name="offeringId" required defaultValue={initialOffering}><option value="" disabled>Choose your degree, school and campus</option>{offerings.filter((item) => item.status === "current").map((item) => <option value={item.id} key={item.id}>{offeringLabel(item)}</option>)}</select></label><label>Current semester<input name="semester" type="number" min="1" max="12" required /></label><label>Expected graduation year<input name="graduationYear" type="number" min={new Date().getFullYear()} max={new Date().getFullYear()+8} required /></label></div></fieldset><fieldset><legend>What you can share <span>02</span></legend><label>Short bio<textarea name="bio" required minLength={30} rows={4} placeholder="A little about you, your NUST experience and interests." /></label><label>Why do you want to mentor?<textarea name="reason" required minLength={30} rows={4} /></label><div className="check-grid"><span>Topics you can discuss</span>{topics.map((topic) => <label key={topic}><input type="checkbox" name="topics" value={topic} /> {topic}</label>)}</div><label>Languages<input name="languages" required placeholder="English, Urdu" /><small>Separate multiple languages with commas.</small></label></fieldset><fieldset><legend>Availability & verification <span>03</span></legend><label>General availability<textarea name="availability" rows={3} required placeholder="For example: Two weekday evenings each month." /></label><label>LinkedIn URL <em>Optional</em><input name="linkedinUrl" type="url" placeholder="https://linkedin.com/in/..." /></label><label className="checkbox-field"><input type="checkbox" name="verificationConsent" required /><span>I consent to PageForward verifying my current NUST student status. I understand my private email and verification details will never appear publicly.</span></label><label className="checkbox-field"><input type="checkbox" name="codeOfConduct" required /><span>I agree to the <Link href="/community-guidelines">mentor code of conduct</Link>, including respectful, neutral and privacy-conscious guidance.</span></label></fieldset><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label>{status === "error" ? <p className="form-error" role="alert">{error}</p> : null}<button className="button form-submit" type="submit" disabled={status === "sending"}>{status === "sending" ? "Sending…" : "Apply to Become a Mentor"}<span>→</span></button></form>;
}
